# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jay's Blog
email: jayaram.h4u@gmail.com
myname: Jayaram Mani
description: > # this means to ignore newlines until "baseurl:"
  Collection of tips, tricks, tech blog and every day tech stuff.
  IBMer, experienced java developer, technical architect.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaymcoder.github.io" # the base hostname & protocol for your site
twitter_username: jaymcoder
github_username:  jaymcoder

# GEMs
gems: [jekyll-assets]

# Build settings
# Assets
assets:
  prefix: "/assets"
  assets:
    - "*.ttf"
  sources:
    - "_assets/fonts"

# SASS
sass:
  sass_dir: _sass

# Plugins
plugins_dir: [jekyll-assets]

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown processor
kramdown:
  input: GFM
